apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-esm4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-esm4
    app.kubernetes.io/part-of: ci10t-786-0089-app
  name: devfile-sample-esm4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-esm4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-esm4
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0089-tenant/ci10t-786-0089-app/devfile-sample-esm4@sha256:bcff386f8988490e3de7e2d4b2994d592bee516e1ad88f04bd640210ce5349b6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
